# Generated by Django 5.2 on 2025-05-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReactions',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'article_id', 'reaction_type_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('reaction_type_id', models.IntegerField()),
                ('reaction_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_reactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('pk', models.CompositePrimaryKey('article_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
            ],
            options={
                'db_table': 'article_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture_url', models.CharField(blank=True, max_length=255, null=True)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentReactions',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'comment_id', 'reaction_type_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('reaction_type_id', models.IntegerField()),
                ('reaction_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment_reactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('article_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReactionTypes',
            fields=[
                ('reaction_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'reaction_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersRoles',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'role_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
            ],
            options={
                'db_table': 'users_roles',
                'managed': False,
            },
        ),
    ]
