# Generated by Django 5.2 on 2025-05-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextera_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usersroles',
            options={'managed': True},
        ),
    ]
