# Generated by Django 5.2.1 on 2025-05-17 09:52

from django.db import migrations

def insert_reactions(apps, shema_editor):
    ReactionType = apps.get_model('nextera_blog', 'ReactionTypes')

    reactions_list = [
        {'reaction_type_id': 1, 'emoji': '👍', 'description': 'Like'},
        {'reaction_type_id': 2, 'emoji': '❤️', 'description': 'Love'},
        {'reaction_type_id': 3, 'emoji': '😂', 'description': 'Funny'},
        {'reaction_type_id': 4, 'emoji': '😮', 'description': 'Surprised'},
        {'reaction_type_id': 5, 'emoji': '😢', 'description': 'Sad'},
        {'reaction_type_id': 6, 'emoji': '😡', 'description': 'Angry'},
        {'reaction_type_id': 7, 'emoji': '👏', 'description': 'Applause'},
        {'reaction_type_id': 8, 'emoji': '🤔', 'description': 'Thoughtful'},
        {'reaction_type_id': 9, 'emoji': '🔥', 'description': 'Hot take'},
        {'reaction_type_id': 10, 'emoji': '💯', 'description': 'Agree 100%'},
    ]

    for reaction_data in reactions_list:
        ReactionType.objects.update_or_create(
            reaction_type_id=reaction_data['reaction_type_id'],
            defaults={
                'emoji': reaction_data['emoji'],
                'description': reaction_data['description'],
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('nextera_blog', '0002_add_roles'),
    ]

    operations = [
        migrations.RunPython(insert_reactions),
    ]
