# Generated by Django 5.2.2 on 2025-06-11 14:03

from django.db import migrations

def insert_tags(apps, shema_editor):
    Tags = apps.get_model('nextera_blog', 'Tags')

    tags_list = [
        {'tag_id': 1, 'name': 'Front'},
        {'tag_id': 2, 'name': 'Back'},
        {'tag_id': 3, 'name': 'Informatique'},
        {'tag_id': 4, 'name': 'Code'},
        {'tag_id': 5, 'name': 'Hardware'},
        {'tag_id': 6, 'name': 'Cyber'},
        {'tag_id': 7, 'name': 'Tips'},
        {'tag_id': 8, 'name': 'IA'},
        {'tag_id': 9, 'name': 'Data'},
        {'tag_id': 10, 'name': 'Infra'},
    ]

    for tag_data in tags_list:
        Tags.objects.update_or_create(
            tag_id=tag_data['tag_id'],
            defaults={
                'name': tag_data['name'],
            }
        )

class Migration(migrations.Migration):


    dependencies = [
        ('nextera_blog', '0003_add_reactions'),
    ]

    operations = [
        migrations.RunPython(insert_tags)
    ]
