SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `nextera`
--
CREATE DATABASE IF NOT EXISTS `nextera` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `nextera`;

-- Création de l'utilisateur Django
DROP USER IF EXISTS 'nextera_user'@'%';
CREATE USER 'nextera_user'@'%' IDENTIFIED WITH mysql_native_password BY 'password'; -- Utilise ton vrai mot de passe de ton .env
GRANT ALL PRIVILEGES ON nextera.* TO 'nextera_user'@'%';
FLUSH PRIVILEGES;

COMMIT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;